-- Repairs a regression introduced by migration
-- 20260831171324_add_location_email: that migration was generated by
-- `prisma migrate dev --create-only` from a schema diff, and because the
-- `duration` generated column + `reservation_no_overlap` EXCLUDE
-- constraint (added in 20260831121500_reservation_no_overlap_constraint)
-- were not represented in schema.prisma at the time, Prisma's diff
-- included an unwanted `DROP COLUMN "duration"` — which cascaded to drop
-- the exclusion constraint with it, silently disabling double-booking
-- protection at the database level.
--
-- The `duration` field is now declared in schema.prisma as
-- `Unsupported("tsrange")` specifically so this cannot recur: Prisma skips
-- diffing Unsupported fields, so it will no longer propose dropping this
-- column in future migrations.

CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE "reservation"
  ADD COLUMN "duration" tsrange
  GENERATED ALWAYS AS (tsrange("startAt", "endAt", '[)')) STORED;

ALTER TABLE "reservation"
  ADD CONSTRAINT "reservation_no_overlap"
  EXCLUDE USING gist (
    "tableId" WITH =,
    "duration" WITH &&
  )
  WHERE ("tableId" IS NOT NULL AND "status" = 'CONFIRMED');
